# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('phone_number', models.CharField(max_length=20, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮件')),
                ('student_id', models.CharField(max_length=20, verbose_name='学号')),
                ('statue', models.FloatField(verbose_name='身高')),
                ('is_male', models.BooleanField(verbose_name='性别')),
                ('grade', models.CharField(max_length=10, verbose_name='年级')),
                ('institute', models.CharField(max_length=20, verbose_name='学院')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('match_zone', models.CharField(max_length=10, verbose_name='参赛地点')),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='team_belongto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Team'),
        ),
    ]
