# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='grade',
            field=models.CharField(max_length=5, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='person',
            name='institute',
            field=models.CharField(max_length=10, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=6, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='person',
            name='student_id',
            field=models.CharField(max_length=12, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='team',
            name='match_zone',
            field=models.CharField(max_length=6, verbose_name='参赛地点'),
        ),
    ]
