# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20170414_0242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '队员', 'verbose_name_plural': '队员'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '队伍', 'verbose_name_plural': '队伍'},
        ),
        migrations.AlterField(
            model_name='team',
            name='match_zone',
            field=models.CharField(choices=[('LX', '良乡校区'), ('ZG', '中关村校区')], max_length=2, verbose_name='参赛地点'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=10, verbose_name='队伍名称'),
        ),
    ]
