# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20170414_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='student_id',
            field=models.CharField(max_length=12, unique=True, verbose_name='学号'),
        ),
    ]
