# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20170414_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='手机号码'),
        ),
    ]
