# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_auto_20170416_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_to_modify', models.BooleanField(default=True, verbose_name='是否允许注册')),
            ],
        ),
    ]
