# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': '注册设置', 'verbose_name_plural': '注册设置'},
        ),
        migrations.AddField(
            model_name='setting',
            name='single_person_team_limited',
            field=models.IntegerField(default=15, verbose_name='单人队伍数量限制'),
        ),
        migrations.AddField(
            model_name='setting',
            name='team_limited_Liangxiang',
            field=models.IntegerField(default=170, verbose_name='良乡报名队伍数量限制'),
        ),
        migrations.AddField(
            model_name='setting',
            name='team_limited_Zhongguancun',
            field=models.IntegerField(default=50, verbose_name='中关村报名队伍数量限制'),
        ),
    ]
