# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_team_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='statue',
        ),
        migrations.AddField(
            model_name='person',
            name='clothing_size',
            field=models.CharField(choices=[('XS', 'XS，身高160cm'), ('S', 'S，身高165cm'), ('M', 'M，身高170cm'), ('L', 'L，身高175cm'), ('XL', 'XL，身高180cm'), ('XXL', 'XXL，身高185cm'), ('XXXL', 'XXXL，身高190cm')], default='', max_length=4, verbose_name='衣服尺码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(max_length=5, null=True, verbose_name='队伍ID'),
        ),
    ]
