# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', tinymce.models.HTMLField()),
                ('pub_date', models.DateTimeField(verbose_name='发布日期')),
                ('author', models.CharField(max_length=40)),
            ],
        ),
    ]
