# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 01:49
from __future__ import unicode_literals

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
