# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170412_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Notice')),
            ],
        ),
    ]
