# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_noticefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='主页标题')),
            ],
            options={
                'verbose_name_plural': '主页',
                'verbose_name': '主页',
            },
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterModelOptions(
            name='noticefile',
            options={'verbose_name': '附件列表', 'verbose_name_plural': '附件列表'},
        ),
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.CharField(max_length=40, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=djrichtextfield.models.RichTextField(verbose_name='通知内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.TextField(verbose_name='通知标题'),
        ),
        migrations.AlterField(
            model_name='noticefile',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='附件'),
        ),
    ]
