# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20170413_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='滚动图片')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.HomePage')),
            ],
            options={
                'verbose_name': '主页滚动图片',
                'verbose_name_plural': '主页滚动图片',
            },
        ),
    ]
