# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 04:17
from __future__ import unicode_literals

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20170413_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_us',
            field=djrichtextfield.models.RichTextField(default='', verbose_name='联系我们内容'),
            preserve_default=False,
        ),
    ]
